---
title: "Chloropleth"
output: pdf_document
date: "2024-03-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r}
library(tidyverse)
library(tmap)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(scales)
```

# Read in data

```{r}
spotify <- read.csv("./data/final.csv")%>% 
  filter(country != "country") %>% 
  filter(country != "Global") %>% 
  dplyr::select(streams, country, danceability, energy, loudness, liveness, acousticness, speechiness, mode, tempo, valence, duration) %>% 
  mutate(streams = as.numeric(streams), danceability = as.numeric(danceability), energy = as.numeric(energy), mode = as.numeric(mode), tempo = as.numeric(tempo), valence = as.numeric(valence), duration = as.numeric(duration))
```

# Group data by country

```{r}
spotify.country <- spotify %>% 
  group_by(country) %>% 
  summarise(streams = sum(streams), danceability = mean(danceability, na.rm = T), energy = mean(energy, na.rm = T), mode = round(mean(mode, na.rm = T), 0), tempo = mean(tempo, na.rm = T), valence = mean(valence, na.rm = T), duration = mean(duration, na.rm = T)) %>% 
  mutate(dance.level = ifelse(danceability >=0 & danceability < 0.33, "low", ifelse(danceability >= 0.33 & danceability < 0.66, "moderate", "high"))) %>% 
  mutate(energy.level = ifelse(energy >=0.5 & energy < 0.6, "low", ifelse(energy >= 0.6 & energy < 0.7, "moderate", "high"))) %>% 
  mutate(streams.level = ifelse(streams >= 0 & streams < 15e9, "low", ifelse(streams >= 15e9 & streams < 30e9, "moderate", ifelse(streams >= 30e9 & streams < 45e9, "high", "sky"))))
```

# Fix country names

```{r}
spotify.country <- spotify.country %>% 
  mutate(country = ifelse(country == "United States", "United States of America", country)) %>% 
  mutate(country = ifelse(country == "Czech Republic", "Czechia", country)) %>% 
  mutate(country = ifelse(country == "Dominican Republic", "Dominican Rep.", country)) %>% 
  mutate(country = ifelse(country == "Korea", "South Korea", country))
```

# Enforce orders

```{r}
# Set danceability order.
dance.order <- c("low", "moderate", "high")
spotify.country <- spotify.country %>% 
  mutate(dance.level = factor(dance.level, levels = dance.order))

# Set streams order.
streams.order <- c("low", "moderate", "high", "sky")
spotify.country <- spotify.country %>% 
  mutate(streams.level = factor(streams.level, levels = streams.order))

# Set energy order.
spotify.country <- spotify.country %>% 
  mutate(energy.level = factor(energy.level, levels = dance.order))

# Set mode order.
mode.order <- c(0, 1)
spotify.country <- spotify.country %>% 
  mutate(mode.level = factor(mode, levels = mode.order))
```

# Get world map data

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf") %>% 
  filter(sovereignt != "Antarctica")
```

# Join world map with Spotify data

```{r}
world.data <- left_join(world, spotify.country, by = c("sovereignt" = "country"))

world.data.dance <- world.data %>% 
  filter(!is.na(danceability))
```


# Setup danceability icons

```{r}
dance.icons = tmap_icons(c("./World Map/public/high-dance.png", 
                        "./World Map/public/moderate-dance.png",
                        "./World Map/public/low-dance.png" 
                        ))
```

# Create chloropleths.

```{r}
breaks <- c(0, 15e9, 30e9, 45e9, 60e9)

streams.energy.dance1 <- tm_shape(world.data, title = "Streams") +
  tm_fill("streams", title = "Streams", palette = "Greens", breaks = breaks) +
  tm_shape(world.data) +
  tm_borders(col = "black", lwd = 0.5) +
  tm_shape(world.data) +
  tm_bubbles("energy", col = "danceability", n = 3,
             style="fixed", 
             breaks=c(0, 0.33, 0.66, 1),
             palette="Blues",
             size = 0.2,
             title.size="Energy", 
             title.col="Danceability") + 
  tm_format("World") + 
  tm_layout(frame = FALSE, legend.position = c("left", "center"), legend.show = F)
streams.energy.dance1

streams.energy.mode.dance <- tm_shape(world.data, title = "Streams") +
  tm_fill("streams", title = "Streams", palette = "Greens", breaks = breaks, colorNA = "orange") +
  tm_shape(world.data) +
  tm_borders(col = "white", lwd = 0.5) +
  tm_shape(world.data) +
  tm_bubbles("mode", 
             col = "energy",
             shape = 21,
             style="fixed", 
             border.lwd = 0.1,
             breaks=c(0.5, 0.6, 0.7, 0.8),
             palette="Blues", 
             title.size="Mode", 
             title.col="Energy",
             sizes.legend = c(0, 1),
             scale = 0.7) + 
  tm_shape(world.data.dance) +
  tm_symbols(shape = "dance.level", shapes = dance.icons, border.lwd = 0, size = 0.2, title.shape = "Danceability", scale = 0.7) +
  tm_layout(frame = FALSE, legend.position = c("left", "center"), legend.show = F, inner.margins = 0, bg.color = "orange")
streams.energy.mode.dance

tmap_save(streams.energy.mode.dance, filename = "./plots/Chloropleth Bubbles T.png", dpi = 1500, scale = 2)
```

```{r}
tmp <- tm_shape(world.data, title = "Streams") +
    tm_fill("streams", title = "Streams", palette = "Greens", breaks = breaks, colorNA = "orange") +
    tm_shape(world.data) +
    tm_borders(col = "white", lwd = 0.5) +
    tm_shape(world.data) +
    tm_bubbles("energy",
               col = "energy",
               shape = 22,
               style = "fixed",
               border.lwd = 0.1,
               breaks = c(0, 0.33, 0.66, 1),
               palette = "Blues",
               title.size = "Energy",
               title.col = "Energy",
               sizes.legend = c(0, 1),
               scale = 0.7) +
    tm_shape(world.data) +
    tm_symbols(shape = "mode", shapes = c(11,21, 23, 24, 25), border.lwd = 0, size = 0.2, title.shape = "Mode", scale = 0.7) +
    tm_shape(world.data.dance) +
    tm_symbols(shape = "dance.level", shapes = dance.icons, border.lwd = 0, size = 0.2, title.shape = "Danceability", scale = 0.7) +
    tm_layout(frame = FALSE, legend.position = c("left", "center"), legend.outside = T, inner.margins = 0, bg.color = "orange")
```


# Distributions

```{r}
# Streams distribution

streams.dist <- spotify.country %>% 
  ggplot(aes(streams.level)) +
  geom_bar(fill="lightgreen", position = position_dodge(width = 0.1)) +
  theme_minimal() +
  labs(x = NULL, y = NULL) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank())
streams.dist

ggsave("./plots/StreamsDist.png", plot = streams.dist, dpi = 300)
```



```{r}
# Mode distribution

mode.dist <- spotify.country %>% 
  ggplot(aes(mode.level)) +
  geom_bar(fill="lightgreen", position = position_dodge(width = 0.1)) +
  theme_minimal() +
  labs(x = NULL, y = NULL) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank())
mode.dist

ggsave("./plots/ModeDist.png", plot = mode.dist, dpi = 300)
```



```{r}
# Energy Distribution

energy.dist <- spotify.country %>% 
  ggplot(aes(energy.level)) +
  geom_bar(fill="lightgreen", position = position_dodge(width = 0.1)) +
  scale_x_discrete(drop = FALSE) +
  theme_minimal() +
  labs(x = NULL, y = NULL) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank())
energy.dist

ggsave("./plots/EnergyDist.png", plot = energy.dist, dpi = 300)
```



```{r}
# Danceability Distribution

danceability.dist <- spotify.country %>% 
  ggplot(aes(dance.level)) +
  geom_bar(fill="lightgreen", position = position_dodge(width = 0.1)) +
  scale_x_discrete(drop = FALSE) +
  theme_minimal() +
  labs(x = NULL, y = NULL) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank())
danceability.dist

ggsave("./plots/DanceDist.png", plot = danceability.dist, dpi = 300)
```

# South Africa Zoom

```{r}
sa <- ne_countries(country = "South Africa", scale = "medium", returnclass = "sf")

sa.data <- left_join(sa, spotify.country, by = c("sovereignt" = "country"))

sa.streams.energy.loud.dance <- tm_shape(sa.data, title = "Streams") +
  tm_fill("streams", title = "Streams", palette = "Greens", breaks = breaks) +
  tm_shape(sa.data) +
  tm_borders(col = "black", lwd = 0.5) +
  tm_shape(sa.data) +
  tm_bubbles("mode", 
             col = "energy",
             shape = 22,
             style="fixed", 
             border.lwd = 0.1,
             breaks=c(0.5, 0.6, 0.7, 0.8),
             palette="Blues", 
             title.size="Mode", 
             title.col="Energy",
             sizes.legend = c(0, 1),
             scale = 0.7) + 
  tm_shape(sa.data) +
  tm_symbols(shape = "dance.level", shapes = dance.icons, border.lwd = 0, alpha  = 0.1, size = 0.2, title.shape = "Danceability") +
  tm_layout(frame = FALSE, legend.position = c("left", "center"), legend.only = T, inner.margins = 0)
sa.streams.energy.loud.dance

tmap_save(sa.streams.energy.loud.dance, filename = "./plots/Chloropleth Bubbles SA.png", dpi = 1500, scale = 2)
```



```{r}
streams.valence.duration.dance <- tm_shape(world.data) +
  tm_fill("valence", title = "Streams", palette = "Greens", breaks = c(0.4, 0.5, 0.6, 0.7), colorNA = "orange") +
  tm_shape(world.data) +
  tm_borders(col = "black", lwd = 0.5) +
  tm_layout(frame = FALSE, legend.position = c("left", "center"), legend.show = F, inner.margins = 0, bg.color = "orange")
streams.valence.duration.dance

tmap_save(streams.valence.duration.dance, filename = "./plots/Chloropleth Valence.png", dpi = 1500, scale = 2)
```

